# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install the package globally
RUN npm install -g @lishenxydlgzs/aws-athena-mcp

# Set default environment variables
ENV TRANSPORT_MODE=sse
ENV PORT=3000
ENV NODE_ENV=production

# Expose the port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1

# Run the server
CMD ["aws-athena-mcp"]
